<center>
    <h1>JaxTon</h1>
    <i>💯 JAX exercises</i>
    <br>
    <br>
    <a href='https://github.com/vopani/jaxton/blob/master/LICENSE'>
        <img src='https://img.shields.io/badge/license-Apache%202.0-blue.svg?logo=apache'>
    </a>
    <a href='https://github.com/vopani/jaxton'>
        <img src='https://img.shields.io/github/stars/vopani/jaxton?color=yellowgreen&logo=github'>
    </a>
    <a href='https://twitter.com/vopani'>
        <img src='https://img.shields.io/twitter/follow/vopani'>
    </a>
</center>

<center>
    This is Set 3: Pseudorandom Numbers (Solutions 21-30) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>

**Prerequisites**

* The configuration of jax should be set as shown in the code snippet below in order to use TPUs.
* A sample array `sample_data` will be used for the exercises.

In [1]:
!python3 -m pip install jax

In [2]:
## import packages
import jax
import jax.numpy as jnp
import os
import requests

## setup JAX to use TPUs if available
try:
    url = 'http:' + os.environ['TPU_NAME'].split(':')[1] + ':8475/requestversion/tpu_driver_nightly'
    resp = requests.post(url)
    jax.config.FLAGS.jax_xla_backend = 'tpu_driver'
    jax.config.FLAGS.jax_backend_target = os.environ['TPU_NAME']
except:
    pass

jax.devices()

[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0),
 TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1),
 TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0),
 TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1),
 TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0),
 TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1),
 TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0),
 TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]

In [3]:
## sample data
sample_data = jnp.array([10, 1, 24, 20, 15, 14])
sample_data

DeviceArray([10,  1, 24, 20, 15, 14], dtype=int32)

**Exercise 21: Create a pseudorandom number generator key with seed=100 and assign it to `key`**

In [4]:
key = jax.random.PRNGKey(100)
key

DeviceArray([  0, 100], dtype=uint32)

**Exercise 22: Create a subkey from `key` and assign it to `subkey`**

In [5]:
key, subkey = jax.random.split(key)
subkey

array([3011861781, 1867493174], dtype=uint32)

**Exercise 23: Split `key` into seven subkeys `key_1`, `key_2`, `key_3`, `key_4`, `key_5`, `key_6` and `key_7`**

In [6]:
key_1, key_2, key_3, key_4, key_5, key_6, key_7 = jax.random.split(key, num=7)
key_1

array([ 402730500, 1595431526], dtype=uint32)

**Exercise 24: Create a random permutation of `sample_data` using `key_1` and assign it to `data_permutation`**

In [7]:
data_permutation = jax.random.permutation(key_1, sample_data)
data_permutation

DeviceArray([20, 14,  1, 10, 24, 15], dtype=int32)

**Exercise 25: Choose a random element from `sample_data` using `key_2` and assign it to `random_selection`**

In [8]:
random_selection = jax.random.choice(key_2, sample_data)
random_selection

DeviceArray(1, dtype=int32)

**Exercise 26: Sample an integer between 10 and 24 using `key_3` and assign it to `sample_int`**

In [9]:
sample_int = jax.random.randint(key_3, shape=(1,), minval=10, maxval=24)
sample_int

DeviceArray([14], dtype=int32)

**Exercise 27: Sample two values from uniform distribution between 1 and 2 using `key_4` and assign it to `sample_uniform`**

In [10]:
sample_uniform = jax.random.uniform(key_4, shape=(2,), minval=1, maxval=2)
sample_uniform

DeviceArray([1.6274643, 1.1133162], dtype=float32)

**Exercise 28: Sample three values from bernoulli distribution using `key_5` and assign it to `sample_bernoulli`**

In [11]:
sample_bernoulli = jax.random.bernoulli(key_5, shape=(3,))
sample_bernoulli

DeviceArray([False,  True,  True], dtype=bool)

**Exercise 29: Sample a 2x3 matrix from poisson distribution with λ=100 using `key_6` and assign it to `sample_poisson`**

In [12]:
sample_poisson = jax.random.poisson(key_6, shape=(2, 3), lam=100)
sample_poisson

DeviceArray([[ 88,  82, 110],
             [ 89,  85,  98]], dtype=int32)

**Exercise 30: Sample a 2x3x4 array from normal distribution using `key_7` and assign it to `sample_normal`**

In [13]:
sample_normal = jax.random.normal(key_7, shape=(2, 3, 4))
sample_normal

DeviceArray([[[ 0.25418088,  1.1962731 ,  1.3234351 ,  0.79711384],
              [-1.8524722 , -0.28634202,  0.2251514 , -0.6195333 ],
              [ 2.4013765 ,  0.07618266,  1.2277839 , -0.7562425 ]],

             [[-0.45340484,  1.1029627 , -0.39860612, -1.1235143 ],
              [-1.5689532 ,  0.4617323 , -0.5607138 , -1.7508575 ],
              [ 0.50200105, -1.4972546 , -1.6995528 ,  0.5555226 ]]],            dtype=float32)

<center>
    This completes Set 3: Pseudorandom Numbers (Solutions 21-30) of <b>JaxTon</b>: <i>💯 JAX exercises</i>
    <br>
    You can find all the exercises and solutions on <a href="https://github.com/vopani/jaxton#exercises-">GitHub</a>
</center>